"""
Publication-ready diverging bar chart of within-group change (Cohen's d, 2020->2023).
Outputs viz/fig_within_group_change.jpg at 300 DPI for direct insertion into the thesis.

Source of truth: code/_effect_sizes.tsv (generated by code/24). For inverted
composites, code/24 applies the scale inversion BEFORE computing means and d,
so the d values stored in the TSV are already in the convention
"positive d = more of the construct, 2020 -> 2023." This script reads d and p
directly from the TSV and applies NO further sign manipulation. The (inv.)
label on a row is purely textual.
"""

import csv
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

ROOT = Path(__file__).parent.parent

# ---------- Read d and p from the canonical TSV --------------------------
tsv_path = ROOT / "code" / "_effect_sizes.tsv"
within = {}  # (variable, group) -> {d, p}
with open(tsv_path) as f:
    for r in csv.DictReader(f, delimiter="\t"):
        if r["table"] != "within":
            continue
        within[(r["variable"], r["comparison"])] = {
            "d": float(r["d"]),
            "p": float(r["p"]),
        }

# ---------- Row order + inverted-label flag ------------------------------
# `inverted` here ONLY controls whether the row label gets "(inv.)" appended.
# It does NOT alter the displayed d, which is read verbatim from the TSV.
rows = [
    # (tsv_name, chart_label, inverted?)
    ("Contact: Russian Speakers",          "Contact: Russian Speakers",          True),
    ("Contact: Estonian Speakers",         "Contact: Estonian Speakers",         True),
    ("SD: Primary Out-group",              "Social Distance: Primary Out-group", False),
    ("Minority Support Inclusion",         "Minority Inclusion Support",         True),
    ("Superordinate Identity",             "Superordinate Identity",             True),
    ("Belief in Inevitable Conflict",      "Belief in Inevitable Conflict",      False),
    ("Comparative Opportunity Assessment", "Comparative Opportunity Assessment", True),
    ("Group ID Patterns",                  "Group ID Patterns",                  False),
    ("SD: General Out-group",              "Social Distance: General Out-group", False),
    ("Territorial Attachment",             "Territorial Attachment",             True),
]

def stars(p):
    if p < 0.001: return "***"
    if p < 0.01:  return "**"
    if p < 0.05:  return "*"
    return "ns"

labels = []
d_est, d_rus = [], []
p_est, p_rus = [], []
for tsv_name, lbl, inv in rows:
    e = within[(tsv_name, "Estonian")]
    r = within[(tsv_name, "Russian")]
    labels.append(lbl + ("  (inv.)" if inv else ""))
    d_est.append(e["d"])
    p_est.append(e["p"])
    d_rus.append(r["d"])
    p_rus.append(r["p"])

n = len(labels)
y_pos = np.arange(n)[::-1]

# ---------- Style ---------------------------------------------------------
plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "font.size":   9,
    "axes.edgecolor": "#333333",
    "axes.linewidth": 0.7,
})

EST = "#2563eb"
RUS = "#d97706"

fig, ax = plt.subplots(figsize=(7.5, 7.4), dpi=300)

bar_h = 0.36
y_est = y_pos + bar_h/2 + 0.02
y_rus = y_pos - bar_h/2 - 0.02

for i in range(n):
    sig_e = p_est[i] < 0.05
    sig_r = p_rus[i] < 0.05
    ax.barh(y_est[i], d_est[i], height=bar_h,
            color=EST, alpha=0.95 if sig_e else 0.30,
            edgecolor=EST, linewidth=0.8 if not sig_e else 0,
            linestyle="-" if sig_e else (0,(3,2)))
    ax.barh(y_rus[i], d_rus[i], height=bar_h,
            color=RUS, alpha=0.95 if sig_r else 0.30,
            edgecolor=RUS, linewidth=0.8 if not sig_r else 0,
            linestyle="-" if sig_r else (0,(3,2)))

for i in range(n):
    for d, y, p in [
        (d_est[i], y_est[i], p_est[i]),
        (d_rus[i], y_rus[i], p_rus[i]),
    ]:
        offset = 0.015 if d >= 0 else -0.015
        ha = "left" if d >= 0 else "right"
        sig = p < 0.05
        ax.text(d + offset, y, f"{d:+.2f} {stars(p)}",
                va="center", ha=ha,
                fontsize=7.5,
                color="#111" if sig else "#888",
                fontweight="bold" if sig else "normal")

for x in [-0.5, -0.2, 0.2, 0.5]:
    ax.axvline(x, color="#cccccc", linewidth=0.6, linestyle=":", zorder=0)
ax.axvline(0, color="#333333", linewidth=0.9, zorder=1)

ax.text( 0.20, -0.55, "small",  ha="center", fontsize=6.5, color="#999", style="italic")
ax.text( 0.50, -0.55, "medium", ha="center", fontsize=6.5, color="#999", style="italic")
ax.text(-0.20, -0.55, "small",  ha="center", fontsize=6.5, color="#999", style="italic")
ax.text(-0.50, -0.55, "medium", ha="center", fontsize=6.5, color="#999", style="italic")

ax.set_yticks(y_pos)
ax.set_yticklabels(labels, fontsize=8.5)
ax.set_ylim(-0.9, n + 0.4)
ax.set_xlim(-0.7, 0.7)
ax.set_xticks([-0.6, -0.4, -0.2, 0, 0.2, 0.4, 0.6])
ax.set_xlabel("Cohen's d (within-group, 2020 → 2023)", fontsize=9.5, labelpad=8)

for s in ("top","right"):
    ax.spines[s].set_visible(False)
ax.spines["left"].set_color("#333333")
ax.spines["bottom"].set_color("#333333")
ax.tick_params(axis="x", length=3, color="#333333")
ax.tick_params(axis="y", length=0)

fig.text(0.05, 0.965, "Within-Group Change in Intergroup Attitudes, 2020 → 2023",
         fontsize=12.5, fontweight="bold", ha="left")
fig.text(0.05, 0.940,
         "Cohen's d for Estonian and Russian respondents across composite and single-item measures",
         fontsize=9, color="#444", ha="left")

est_patch = mpatches.Patch(color=EST, label="Estonian respondents")
rus_patch = mpatches.Patch(color=RUS, label="Russian respondents")
sig_patch = mpatches.Patch(facecolor="white", edgecolor="#666",
                           label="Faded bars: not significant (p ≥ .05)")
fig.legend(handles=[est_patch, rus_patch, sig_patch],
           loc="upper left", bbox_to_anchor=(0.03, 0.915),
           frameon=False, fontsize=8,
           handlelength=1.4, handleheight=1.0, ncol=1)

fig.text(0.05, 0.020,
         "(inv.) = scale inverted so that positive d indicates more of the construct (e.g., more belonging, more contact).\n"
         "Significance: *** p<.001, ** p<.01, * p<.05, ns = not significant. d uses root-mean-square SD: "
         r"$d = (M_1 - M_2) / \sqrt{(SD_1^2 + SD_2^2)/2}$.",
         fontsize=7, color="#555", ha="left")

plt.subplots_adjust(left=0.37, right=0.97, top=0.89, bottom=0.12)

out_path = ROOT / "viz" / "fig_within_group_change.jpg"
plt.savefig(out_path, dpi=300, format="jpg",
            facecolor="white", pil_kwargs={"quality": 95})
print(f"Saved: {out_path}")

print("\nValues used (sourced from _effect_sizes.tsv):")
print(f"  {'Variable':<40} {'Est d':>10} {'Est p':>10} {'Rus d':>10} {'Rus p':>10}")
for i, (tsv_name, lbl, inv) in enumerate(rows):
    print(f"  {lbl + (' (inv.)' if inv else ''):<40} "
          f"{d_est[i]:+10.4f} {p_est[i]:10.4f} "
          f"{d_rus[i]:+10.4f} {p_rus[i]:10.4f}")
