"""
Publication-ready diverging bar chart of between-group difference (Cohen's d,
Estonian vs. Russian) in 2020 and 2023. Outputs viz/fig_between_group_gap.jpg
at 300 DPI for direct insertion into the thesis.

Companion to fig_within_group_change.jpg — same visual grammar so the two
charts read together: the within-group chart shows how each group moved
2020->2023; this chart shows the size of the gap between groups in each year.

Source of truth: code/_effect_sizes.tsv (generated by code/24). For inverted
composites, code/24 applies the scale inversion BEFORE computing means and d,
so the d values stored in the TSV are already in the convention
"positive d = Estonian respondents score higher on the construct (e.g. more
belonging, more contact)." This script reads d and p directly from the TSV
and applies NO further sign manipulation. The (inv.) label on a row is purely
textual — it tells the reader the named construct's natural direction was
flipped relative to the survey scale.
"""

import csv
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import numpy as np

ROOT = Path(__file__).parent.parent

# ---------- Read d and p from the canonical TSV --------------------------
tsv_path = ROOT / "code" / "_effect_sizes.tsv"
between = {}  # (variable, year) -> {d, p}
with open(tsv_path) as f:
    reader = csv.DictReader(f, delimiter="\t")
    for r in reader:
        if r["table"] != "between":
            continue
        between[(r["variable"], r["comparison"])] = {
            "d": float(r["d"]),
            "p": float(r["p"]),
        }

# ---------- Row order + inverted-label flag ------------------------------
# `inverted` here ONLY controls whether the row label gets "(inv.)" appended.
# It does NOT alter the displayed d value, which comes verbatim from the TSV.
# The flag must match code/24's per-variable `inverted` setting so labelling
# stays consistent with what the TSV's d direction actually represents.
rows = [
    # (variable_name_in_TSV, label_for_chart, inverted?)
    ("Contact: Russian Speakers",          "Contact: Russian Speakers",         True),
    ("Contact: Estonian Speakers",         "Contact: Estonian Speakers",        True),
    ("SD: Primary Out-group",              "Social Distance: Primary Out-group", False),
    ("Minority Support Inclusion",         "Minority Inclusion Support",        True),
    ("Superordinate Identity",             "Superordinate Identity",            True),
    ("Belief in Inevitable Conflict",      "Belief in Inevitable Conflict",     False),
    ("Comparative Opportunity Assessment", "Comparative Opportunity Assessment", True),
    ("Group ID Patterns",                  "Group ID Patterns",                 False),
    ("SD: General Out-group",              "Social Distance: General Out-group", False),
    ("Territorial Attachment",             "Territorial Attachment",            True),
]

def stars(p):
    if p < 0.001: return "***"
    if p < 0.01:  return "**"
    if p < 0.05:  return "*"
    return "ns"

labels   = []
d_2020, d_2023 = [], []
p_2020, p_2023 = [], []
for tsv_name, lbl, inv in rows:
    r20 = between[(tsv_name, "2020")]
    r23 = between[(tsv_name, "2023")]
    labels.append(lbl + ("  (inv.)" if inv else ""))
    d_2020.append(r20["d"])
    d_2023.append(r23["d"])
    p_2020.append(r20["p"])
    p_2023.append(r23["p"])

n = len(labels)
y_pos = np.arange(n)[::-1]              # top row = first item

# ---------- Style ---------------------------------------------------------
plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "font.size":   9,
    "axes.edgecolor": "#333333",
    "axes.linewidth": 0.7,
})

# Year palette: lighter for 2020 (past), darker for 2023 (focus year)
C2020 = "#94a3b8"   # slate-400 — neutral past
C2023 = "#1e3a8a"   # blue-900  — present/focus

fig, ax = plt.subplots(figsize=(7.5, 7.4), dpi=300)

bar_h = 0.36
y_2020 = y_pos + bar_h/2 + 0.02
y_2023 = y_pos - bar_h/2 - 0.02

# Bars
for i in range(n):
    sig_20 = p_2020[i] < 0.05
    sig_23 = p_2023[i] < 0.05
    ax.barh(y_2020[i], d_2020[i], height=bar_h,
            color=C2020, alpha=0.95 if sig_20 else 0.30,
            edgecolor=C2020, linewidth=0.8 if not sig_20 else 0,
            linestyle="-" if sig_20 else (0,(3,2)))
    ax.barh(y_2023[i], d_2023[i], height=bar_h,
            color=C2023, alpha=0.95 if sig_23 else 0.30,
            edgecolor=C2023, linewidth=0.8 if not sig_23 else 0,
            linestyle="-" if sig_23 else (0,(3,2)))

# d labels at end of bars
for i in range(n):
    for d, y, p in [
        (d_2020[i], y_2020[i], p_2020[i]),
        (d_2023[i], y_2023[i], p_2023[i]),
    ]:
        offset = 0.04 if d >= 0 else -0.04
        ha = "left" if d >= 0 else "right"
        sig = p < 0.05
        ax.text(d + offset, y, f"{d:+.2f} {stars(p)}",
                va="center", ha=ha,
                fontsize=7.5,
                color="#111" if sig else "#888",
                fontweight="bold" if sig else "normal")

# Reference lines
for x in [-2, -1.5, -1, -0.5, 0.5, 1, 1.5, 2]:
    ax.axvline(x, color="#cccccc", linewidth=0.6, linestyle=":", zorder=0)
ax.axvline(0, color="#333333", linewidth=0.9, zorder=1)

# Directional key above the bars: which side means which group scored higher.
# Text label sits above a thin horizontal arrow on each side of the center line.
KEY_Y_ARROW = n + 0.20
KEY_Y_TEXT  = n + 0.55
ax.annotate("", xy=(-2.55, KEY_Y_ARROW), xytext=(-0.10, KEY_Y_ARROW),
            arrowprops=dict(arrowstyle="->", color="#d97706",
                            lw=1.5, shrinkA=0, shrinkB=0))
ax.annotate("", xy=(2.55, KEY_Y_ARROW), xytext=(0.10, KEY_Y_ARROW),
            arrowprops=dict(arrowstyle="->", color="#2563eb",
                            lw=1.5, shrinkA=0, shrinkB=0))
ax.text(-1.32, KEY_Y_TEXT, "Russian respondents scored higher",
        ha="center", va="center", fontsize=8.0,
        color="#d97706", fontweight="bold")
ax.text(1.32, KEY_Y_TEXT, "Estonian respondents scored higher",
        ha="center", va="center", fontsize=8.0,
        color="#2563eb", fontweight="bold")

# Effect-size benchmark annotations (placed just below x-axis line).
for x, lbl in [(-2.0, "very large"), (-0.8, "large"), (-0.5, "medium"),
               (0.5, "medium"), (0.8, "large"), (2.0, "very large")]:
    ax.text(x, -0.55, lbl, ha="center", fontsize=6.5, color="#999", style="italic")

# Axes
ax.set_yticks(y_pos)
ax.set_yticklabels(labels, fontsize=8.5)
ax.set_ylim(-0.9, n + 1.1)
ax.set_xlim(-2.7, 2.7)
ax.set_xticks([-2.5, -2, -1.5, -1, -0.5, 0, 0.5, 1, 1.5, 2, 2.5])
ax.set_xlabel(
    "Cohen's d (between-group: Estonian vs. Russian respondents)",
    fontsize=9.5, labelpad=8
)

# Spines
for s in ("top", "right"):
    ax.spines[s].set_visible(False)
ax.spines["left"].set_color("#333333")
ax.spines["bottom"].set_color("#333333")
ax.tick_params(axis="x", length=3, color="#333333")
ax.tick_params(axis="y", length=0)

# Title and subtitle
fig.text(0.05, 0.965, "Between-Group Difference in Intergroup Attitudes, 2020 and 2023",
         fontsize=12.5, fontweight="bold", ha="left")
fig.text(0.05, 0.940,
         "Cohen's d comparing Estonian and Russian respondents in each year, across composite and single-item measures",
         fontsize=9, color="#444", ha="left")

# Legend (upper-left, matching within-group chart layout)
patch_2020 = mpatches.Patch(color=C2020, label="2020")
patch_2023 = mpatches.Patch(color=C2023, label="2023")
patch_sig  = mpatches.Patch(facecolor="white", edgecolor="#666",
                            label="Faded bars: not significant (p ≥ .05)")
fig.legend(handles=[patch_2020, patch_2023, patch_sig],
           loc="upper left", bbox_to_anchor=(0.03, 0.915),
           frameon=False, fontsize=8,
           handlelength=1.4, handleheight=1.0, ncol=1)

# Footnote
fig.text(0.05, 0.020,
         "(inv.) = scale inverted so that positive d indicates Estonian respondents score higher on the construct (e.g., more belonging, more contact).\n"
         "Significance: *** p<.001, ** p<.01, * p<.05, ns = not significant. d uses root-mean-square SD: "
         r"$d = (M_{Est} - M_{Rus}) / \sqrt{(SD_1^2 + SD_2^2)/2}$.",
         fontsize=7, color="#555", ha="left")

plt.subplots_adjust(left=0.37, right=0.97, top=0.89, bottom=0.12)

out_path = ROOT / "viz" / "fig_between_group_gap.jpg"
plt.savefig(out_path, dpi=300, format="jpg",
            facecolor="white", pil_kwargs={"quality": 95})
print(f"Saved: {out_path}")

# Print verification table
print("\nValues used (sourced from _effect_sizes.tsv):")
print(f"  {'Variable':<40} {'2020 d':>10} {'2020 p':>10} {'2023 d':>10} {'2023 p':>10}")
for i, (tsv_name, lbl, inv) in enumerate(rows):
    print(f"  {lbl + (' (inv.)' if inv else ''):<40} "
          f"{d_2020[i]:+10.4f} {p_2020[i]:10.4f} "
          f"{d_2023[i]:+10.4f} {p_2023[i]:10.4f}")
