"""
Publication-ready dumbbell chart of between-group differences (Estonian vs.
Russian respondents) in 2020 and 2023.

Three-column layout per row: variable name | dumbbell plot | Cohen's d.
For each variable, two horizontal dumbbells stacked:
  - 2020 (lighter, dashed connector, open dots)
  - 2023 (darker, solid connector, filled dots)

Source of truth: code/_effect_sizes.tsv (generated by code/24). Means and d
are read verbatim from the TSV — code/24 has already applied the scale
inversion for variables marked inv=True, so means and d are in the convention
"higher = more of the construct."

Outputs viz/fig_between_group_dumbbell.jpg at 300 DPI.
"""

import csv
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.lines as mlines

ROOT = Path(__file__).parent.parent

# ---------- Read M and d from the canonical TSV --------------------------
tsv_path = ROOT / "code" / "_effect_sizes.tsv"
between = {}
with open(tsv_path) as f:
    for r in csv.DictReader(f, delimiter="\t"):
        if r["table"] != "between":
            continue
        between[(r["variable"], r["comparison"])] = {
            "M_est": float(r["M1"]), "SD_est": float(r["SD1"]), "N_est": int(r["N1"]),
            "M_rus": float(r["M2"]), "SD_rus": float(r["SD2"]), "N_rus": int(r["N2"]),
            "d": float(r["d"]),
            "p": float(r["p"]),
        }

# ---------- Variable metadata --------------------------------------------
# (tsv_name, chart_label, scale_max, inverted?). scale_min is always 1.
# scale_max + inverted MUST match code/24's per-variable settings — the TSV
# means are already on the inverted scale where applicable.
META = [
    ("Contact: Russian Speakers",          "Contact: Russian Speakers",          5, True),
    ("Contact: Estonian Speakers",         "Contact: Estonian Speakers",         5, True),
    ("SD: Primary Out-group",              "Social Distance: Primary Out-group", 5, False),
    ("Minority Support Inclusion",         "Minority Inclusion Support",         4, True),
    ("Superordinate Identity",             "Superordinate Identity",             4, True),
    ("Belief in Inevitable Conflict",      "Belief in Inevitable Conflict",      4, False),
    ("Comparative Opportunity Assessment", "Comparative Opportunity Assessment", 5, True),
    ("Contact: Out-group",                 "Contact: Out-group",                 5, True),
    ("Group ID Patterns",                  "Group ID Patterns",                  5, False),
    ("SD: General Out-group",              "Social Distance: General Out-group", 5, False),
    ("Territorial Attachment",             "Territorial Attachment",             4, True),
]

def stars(p):
    if p < 0.001: return "***"
    if p < 0.01:  return "**"
    if p < 0.05:  return "*"
    return "ns"

# Build per-row plotting data
rows = []
for tsv_name, lbl, smax, inv in META:
    r20 = between[(tsv_name, "2020")]
    r23 = between[(tsv_name, "2023")]
    rows.append({
        "label": lbl,
        "smin": 1, "smax": smax,
        "e20": r20["M_est"], "r20": r20["M_rus"],
        "e23": r23["M_est"], "r23": r23["M_rus"],
        "d20": abs(r20["d"]), "d23": abs(r23["d"]),
        "s20": stars(r20["p"]), "s23": stars(r23["p"]),
        "scale_note": "(inv.)" if inv else "",
    })

# ---------- Style ---------------------------------------------------------
plt.rcParams.update({
    "font.family": "DejaVu Sans",
    "font.size":   9,
    "axes.edgecolor": "#333333",
    "axes.linewidth": 0.6,
})

EST       = "#2563eb"
RUS       = "#d97706"
LINE_2020 = "#9ca3af"
LINE_2023 = "#1f2937"

n = len(rows)

fig = plt.figure(figsize=(9.0, 11.0), dpi=300)
gs = gridspec.GridSpec(
    n, 3,
    width_ratios=[1.7, 4.0, 1.2],
    wspace=0.10, hspace=0.65,
    left=0.03, right=0.985, top=0.905, bottom=0.075
)

for i, row in enumerate(rows):
    name = row["label"]
    smin, smax = row["smin"], row["smax"]
    e20, r20 = row["e20"], row["r20"]
    e23, r23 = row["e23"], row["r23"]
    d20, d23 = row["d20"], row["d23"]
    s20, s23 = row["s20"], row["s23"]
    scale_note = row["scale_note"]

    # --- Column 1: variable name ----------------------------------------
    ax_l = fig.add_subplot(gs[i, 0])
    ax_l.axis("off")
    line1, line2 = name, None
    if len(name) > 22:
        if ":" in name:
            head, tail = name.split(":", 1)
            line1, line2 = head.strip() + ":", tail.strip()
        else:
            words = name.split(" ")
            best, best_diff = 0, 1e9
            for k in range(1, len(words)):
                left = " ".join(words[:k])
                right = " ".join(words[k:])
                diff = abs(len(left) - len(right))
                if diff < best_diff:
                    best, best_diff = k, diff
            line1 = " ".join(words[:best])
            line2 = " ".join(words[best:])
    if line2:
        ax_l.text(0.98, 0.66, line1, ha="right", va="center",
                  fontsize=9.7, fontweight="bold", color="#111", transform=ax_l.transAxes)
        ax_l.text(0.98, 0.43, line2, ha="right", va="center",
                  fontsize=9.7, fontweight="bold", color="#111", transform=ax_l.transAxes)
        ax_l.text(0.98, 0.18, f"Scale {smin}–{smax}  {scale_note}".strip(),
                  ha="right", va="center", fontsize=7.2, color="#666",
                  style="italic", transform=ax_l.transAxes)
    else:
        ax_l.text(0.98, 0.55, line1, ha="right", va="center",
                  fontsize=9.7, fontweight="bold", color="#111", transform=ax_l.transAxes)
        ax_l.text(0.98, 0.27, f"Scale {smin}–{smax}  {scale_note}".strip(),
                  ha="right", va="center", fontsize=7.2, color="#666",
                  style="italic", transform=ax_l.transAxes)

    # --- Column 2: dumbbell plot ----------------------------------------
    ax = fig.add_subplot(gs[i, 1])

    Y_2020, Y_2023 = 1.0, 0.0

    ax.plot([min(e20, r20), max(e20, r20)], [Y_2020, Y_2020],
            color=LINE_2020, linestyle=(0, (3, 2)), linewidth=1.4, alpha=0.85, zorder=1)
    ax.plot([min(e23, r23), max(e23, r23)], [Y_2023, Y_2023],
            color=LINE_2023, linestyle="-", linewidth=1.6, alpha=0.95, zorder=1)

    ax.scatter([e20], [Y_2020], s=80, facecolors="white",
               edgecolors=EST, linewidths=1.7, zorder=3)
    ax.scatter([r20], [Y_2020], s=80, facecolors="white",
               edgecolors=RUS, linewidths=1.7, zorder=3)
    ax.scatter([e23], [Y_2023], s=85, color=EST, edgecolors="white",
               linewidths=0.8, zorder=3)
    ax.scatter([r23], [Y_2023], s=85, color=RUS, edgecolors="white",
               linewidths=0.8, zorder=3)

    OVERLAP_THRESHOLD = 0.30

    def place_pair(v_est, v_rus, y, dy):
        close = abs(v_est - v_rus) < OVERLAP_THRESHOLD
        nudge_y = +0.18 if dy > 0 else -0.18
        if close:
            if v_est <= v_rus:
                left_x, left_c = v_est, EST
                right_x, right_c = v_rus, RUS
            else:
                left_x, left_c = v_rus, RUS
                right_x, right_c = v_est, EST
            ax.text(left_x - 0.05, y + nudge_y, f"{left_x:.2f}",
                    ha="right", va="center", fontsize=7.4,
                    color=left_c, fontweight="bold")
            ax.text(right_x + 0.05, y + nudge_y, f"{right_x:.2f}",
                    ha="left", va="center", fontsize=7.4,
                    color=right_c, fontweight="bold")
        else:
            ax.text(v_est, y + dy, f"{v_est:.2f}",
                    ha="center", va="center", fontsize=7.4,
                    color=EST, fontweight="bold")
            ax.text(v_rus, y + dy, f"{v_rus:.2f}",
                    ha="center", va="center", fontsize=7.4,
                    color=RUS, fontweight="bold")

    place_pair(e20, r20, Y_2020, +0.62)
    place_pair(e23, r23, Y_2023, -0.62)

    ax.text(0.005, Y_2020, "2020", ha="left", va="center",
            fontsize=7.4, color="#666", transform=ax.get_yaxis_transform())
    ax.text(0.005, Y_2023, "2023", ha="left", va="center",
            fontsize=7.6, color="#222", fontweight="bold",
            transform=ax.get_yaxis_transform())

    pad_left = (smax - smin) * 0.08
    ax.set_xlim(smin - pad_left, smax + 0.05)
    ax.set_ylim(-1.1, 2.1)
    ax.set_yticks([])

    xticks = list(range(int(smin), int(smax) + 1))
    ax.set_xticks(xticks)
    ax.tick_params(axis="x", length=2.5, color="#888", labelsize=6.8, pad=2,
                   labelcolor="#666")

    for xt in xticks:
        ax.axvline(xt, color="#e5e7eb", linewidth=0.5, zorder=0)

    for s in ("top", "right", "left"):
        ax.spines[s].set_visible(False)
    ax.spines["bottom"].set_color("#cccccc")
    ax.spines["bottom"].set_linewidth(0.5)

    # --- Column 3: Cohen's d ---------------------------------------------
    ax_r = fig.add_subplot(gs[i, 2])
    ax_r.axis("off")
    ax_r.text(0.05, 0.66, f"d = {d20:.2f} {s20}",
              ha="left", va="center", fontsize=8.0,
              color="#777" if s20 == "ns" else "#222",
              fontweight="normal" if s20 == "ns" else "bold",
              transform=ax_r.transAxes)
    ax_r.text(0.05, 0.34, f"d = {d23:.2f} {s23}",
              ha="left", va="center", fontsize=8.0,
              color="#777" if s23 == "ns" else "#222",
              fontweight="normal" if s23 == "ns" else "bold",
              transform=ax_r.transAxes)

# ---------- Title, subtitle, legend, footnote ----------
fig.text(0.03, 0.965,
         "Between-Group Difference in Intergroup Attitudes, 2020 and 2023",
         fontsize=13, fontweight="bold", ha="left")
fig.text(0.03, 0.946,
         "Estonian (blue) vs. Russian (amber) respondent means on each variable's own scale, with Cohen's d",
         fontsize=9, color="#444", ha="left")

est_dot = mlines.Line2D([], [], marker="o", color="white",
                        markerfacecolor=EST, markeredgecolor=EST,
                        markersize=8, linestyle="None", label="Estonian respondents")
rus_dot = mlines.Line2D([], [], marker="o", color="white",
                        markerfacecolor=RUS, markeredgecolor=RUS,
                        markersize=8, linestyle="None", label="Russian respondents")
y20_line = mlines.Line2D([], [], marker="o", color=LINE_2020,
                         markerfacecolor="white", markeredgecolor="#666",
                         markersize=7, linestyle=(0, (3, 2)),
                         linewidth=1.4, label="2020 (open dots, dashed)")
y23_line = mlines.Line2D([], [], marker="o", color=LINE_2023,
                         markerfacecolor="#444", markeredgecolor="#444",
                         markersize=7, linestyle="-",
                         linewidth=1.6, label="2023 (filled dots, solid)")
fig.legend(handles=[est_dot, rus_dot, y20_line, y23_line],
           loc="upper center", bbox_to_anchor=(0.5, 0.928),
           frameon=False, fontsize=8, handlelength=2.4,
           handleheight=1.0, ncol=4, columnspacing=2.2)

fig.text(0.03, 0.035,
         "Means are shown on each variable's natural scale. Variables marked (inv.) were inverted so that higher values represent more of the construct",
         fontsize=7.0, color="#555", ha="left")
fig.text(0.03, 0.018,
         "(e.g., more belonging, more contact). Cohen's d uses root-mean-square SD: "
         r"$d = (M_{Est} - M_{Rus}) / \sqrt{(SD_1^2 + SD_2^2)/2}$"
         ".  Significance: *** p<.001, ** p<.01, * p<.05, ns = not significant.",
         fontsize=7.0, color="#555", ha="left")

out_path = ROOT / "viz" / "fig_between_group_dumbbell.jpg"
plt.savefig(out_path, dpi=300, format="jpg",
            facecolor="white", pil_kwargs={"quality": 95})
print(f"Saved: {out_path}")
